#!/bin/bash

TARGET="dist-$1"

autoconf
autoheader
automake
#./configure

CONFIGURE="--prefix=/opt/vpe --sysconfdir=/etc --localstatedir=/var --enable-tcp --enable-http-proxy"

eval $(grep VERSION= configure)

mkdir -p $TARGET

BASE=/tmp
MAKE=make

case "$1" in
   gnu-linux )
      HOST=root@localhost
      CONFIGURE="$CONFIGURE --enable-icmp"
   ;;
   freebsd )
      HOST=root@192.168.108.4
      CONFIGURE="$CONFIGURE --enable-icmp"
      MAKE=gmake
   ;;
   openbsd )
      HOST=root@192.168.108.6
      CONFIGURE="$CONFIGURE --enable-icmp"
   ;;
   netbsd )
      HOST=root@192.168.108.5
      CONFIGURE="$CONFIGURE --enable-icmp --with-openssl-include=/usr/local/ssl/include --with-openssl-lib=/usr/local/ssl/lib"
   ;;
   darwin )
      HOST=root@imac.laendle
      BASE=/Users/schmorp
      CONFIGURE="$CONFIGURE --enable-icmp --with-openssl-include=$BASE/include"
      MAKE="make LIBS='$BASE/lib/libcrypto.a -lintl'"
   ;;
   cygwin )
      HOST=vm
      CONFIGURE="$CONFIGURE --enable-icmp"
   ;;
   * )
      exit 1
   ;;
esac

make distdir="$TARGET/vpe" distdir
rsync -avzPessh $TARGET/vpe $HOST:$BASE/. --delete
rm -rf $TARGET/vpe

echo "$CONFIGURE" >$TARGET/configure

ssh $HOST "
   cd $BASE/vpe || exit 1;
   ./configure $CONFIGURE || exit 2;
   rm -rf $BASE/dist;
   $MAKE all || exit 3;
   $MAKE prefix=$BASE/dist install || exit 4;
   strip $BASE/dist/sbin/vped $BASE/dist/bin/vpectrl;
   strip $BASE/dist/sbin/vped.exe $BASE/dist/bin/vpectrl.exe;
   echo vpectrl;
   ldd $BASE/dist/bin/vpectrl;
   echo vped;
   ldd $BASE/dist/sbin/vped;
   uname -a
   true;
" 2>&1 | tee $TARGET/buildlog || exit 1

mkdir -p $TARGET/opt
rsync -avzPessh $HOST:$BASE/dist/. $TARGET/opt/. --delete
(
   cd $TARGET || exit 99
   mkdir opt/doc
   mkdir opt/doc/vped
   mv buildlog opt/doc/vped/README.buildlog
   mv configure opt/doc/vped/README.configure
   chmod u=rwX,go=rX -R opt
)

mkdir -p bindist
tar cCf $TARGET - . | gzip -9 >bindist/vpe-$VERSION-$1.tar.gz

