#!/bin/bash

TARGET="dist-$1"

autoconf
autoheader
automake
#./configure

CONFIGURE="--prefix=/opt/gvpe --sysconfdir=/etc --localstatedir=/var --enable-tcp --enable-http-proxy"

eval $(grep VERSION= configure)

mkdir -p $TARGET

BASE=/tmp
MAKE=make
ARCH="$1"

case "$ARCH" in
   gnu-linux )
      HOST=root@localhost
      CONFIGURE="$CONFIGURE --enable-icmp"
   ;;
   freebsd )
      HOST=root@192.168.108.6
      CONFIGURE="$CONFIGURE --enable-icmp"
      MAKE=gmake
      ARCH="$ARCH-x86"
   ;;
   openbsd )
      HOST=root@192.168.108.7
      CONFIGURE="$CONFIGURE --enable-icmp"
      ARCH="$ARCH-x86"
   ;;
   netbsd )
      HOST=root@192.168.108.5
      CONFIGURE="$CONFIGURE --enable-icmp --with-openssl-include=/usr/local/ssl/include --with-openssl-lib=/usr/local/ssl/lib"
      ARCH="$ARCH-x86"
   ;;
   darwin )
      HOST=root@imac.laendle
      BASE=/Users/schmorp
      CONFIGURE="$CONFIGURE --enable-icmp --with-openssl-include=$BASE/include --with-libintl-prefix=/sw"
      MAKE="make LIBS='$BASE/lib/libcrypto.a -L/sw/lib -lintl'"
      ARCH="$ARCH-x86"
   ;;
   cygwin )
      HOST=vm
      CONFIGURE="$CONFIGURE --enable-icmp"
   ;;
   * )
      exit 1
   ;;
esac

make distdir="$TARGET/gvpe" distdir
rsync -avzPessh $TARGET/gvpe $HOST:$BASE/. --delete
rm -rf $TARGET/gvpe

echo "$CONFIGURE" >$TARGET/configure

ssh $HOST "
   set -x
   cd $BASE/gvpe || exit 1;
   ./configure $CONFIGURE || exit 2;
   rm -rf $BASE/dist;
   $MAKE all || exit 3;
   $MAKE prefix=$BASE/dist install || exit 4;
   strip $BASE/dist/sbin/gvpe $BASE/dist/bin/gvpectrl;
   strip $BASE/dist/sbin/gvpe.exe $BASE/dist/bin/gvpectrl.exe;
   echo gvpectrl;
   ldd $BASE/dist/bin/gvpectrl;
   echo gvpe;
   ldd $BASE/dist/sbin/gvpe;
   uname -a
   true;
" 2>&1 | tee $TARGET/buildlog || exit 1

mkdir -p $TARGET/opt
rsync -avzPessh $HOST:$BASE/dist/. $TARGET/opt/. --delete
(
   cd $TARGET || exit 99
   mkdir opt/doc
   mkdir opt/doc/gvpe
   mv buildlog opt/doc/gvpe/README.buildlog
   mv configure opt/doc/gvpe/README.configure
   chmod u=rwX,go=rX -R opt
)

mkdir -p bindist
tar cCf $TARGET - . | gzip -9 >bindist/gvpe-$VERSION-$ARCH.tar.gz
rm -rf $TARGET

