=head1 NAME

C<vped> - Virtual Private Ethernet Daemon
=head1 SYNOPSIS

C<vped> [B<-cDlL>] [B<--config=>I<DIR>] [B<--no-detach>] [B<-l=>I<LEVEL]>]
[B<--kill>[B<=>I<SIGNAL>]] [B<--mlock>] [B<--help>] [B<--version>]
I<NODENAME>

=head1 DESCRIPTION

This is the manual page for vped, the virtual private ethernet daemon.
When started, C<vped> will read it's configuration file to determine the
network topology, and other configuration information, assuming the role
of node I<NODENAME>. It will then connect to the tun/tap device and set
up a socket for incoming connections.  Then a script will be executed to
further configure the virtual device.  If that succeeds, it will detach
from the controlling terminal and continue in the background, accepting
and setting up connections to other vped daemons that are part of the
virtual private ethernet.

=head1 OPTIONS

=over 4

=item B<-c>, B<--config=>I<DIR>

Read configuration options from I<DIR>

=item B<-d>, B<--l=>I<LEVEL>

Set logging level to I<LEVEL> (one of: noise, trace, debug, info, notice,
warn, error, critical).

=item B<--help>

Display short list of options.

=item B<-D>, B<--no-detach>

Don't fork and detach but stay in foreground and log messages to stderr in
addition to syslog.

=item B<-L>, B<--mlock>

Lock C<vped> into main memory.  This will prevent sensitive data like
shared private keys to be written to the system swap files/partitions.

=item B<--version>

Output version information and exit.

=back

=head1 SIGNALS

=over 4

=item HUP

Closes/resets all connections, resets the retry time and will start connecting
again (it will NOT re-read the config file). This is useful e.g. in a
C</etc/ppp/if-up> script.

=item TERM

Closes/resets all connections and exits.

=item USR1

Dump current network status into the syslog (at loglevel C<notice>, so make
sure your lgolevel allows this).

=back

=head1 FILES

=over 4

=item C</etc/vpe/vped.conf>

The configuration file for C<vped>.

=item C</etc/vpe/if-up>

Script which is executed as soon as the virtual network device has been
allocated.  Purpose is to further configure that device.

=item C</etc/vpe/node-up>

Script which is executed whenever a node connects to this node. This can
be used for example to run nsupdate.

=item C</etc/vpe/node-down>

Script which is executed whenever a conenction to another node is lost.
for example to run nsupdate.

=item C</etc/vpe/pubkey/*>

The directory containing the public keys for every node, usually
autogenerated by executing C<vpectrl --generate-keys>.

=item C</var/run/vped.pid>

The PID of the currently running C<vped> is stored in this file.

=back

=head1 BUGS

The cryptography in vped is not thoroughly checked by many people yet. Use
it at your own risk!

If you find any bugs, report them to C<vpe@plan9.de>.

=head1 TODO

A lot.

=head1 SEE ALSO

vpe(5), vped.conf(5), vpectrl(8).

vpe comes with ABSOLUTELY NO WARRANTY.  This is free software, and you are
welcome to redistribute it under certain conditions; see the file COPYING
for details.

=head1 AUTHORS

Marc Lehmann C<< <vpe@plan9.de> >>.

And thanks to many others for their contributions to vpe, especially the
tincd authors, who inspired me to write this program (after scavenging
their sourcecode ;).

